# Generated by Django 2.2.5 on 2019-12-20 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nodeStatus', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='node',
            name='device',
            field=models.CharField(max_length=120),
        ),
    ]
