# Generated by Django 2.2.5 on 2019-12-20 03:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nodeStatus', '0002_auto_20191220_0314'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='node',
            new_name='nodeMQTT',
        ),
    ]
