# Generated by Django 2.2.5 on 2019-12-20 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nodeStatus', '0003_auto_20191220_0321'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nodemqtt',
            name='last_msg',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name='nodemqtt',
            name='role',
            field=models.CharField(default='subcriber', max_length=120),
        ),
    ]
